FROM python:3

WORKDIR /home/logan/Projects/408-Project

RUN pip install --no-cache-dir --upgrade pip && \
    pip install open3d \
    pip install py-pde \
    pip install h5py pandas mpi4py numba-mpi

COPY . .